name = "Gamma"
uuid = "a0844989-3bd2-4988-8bea-c9407ab0941b"
version = "1.1.0"

[deps]

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[extensions]
GammaForwardDiffExt = "ForwardDiff"
GammaChainRulesCoreExt = "ChainRulesCore"

[compat]
SpecialFunctions = "2.7.2"
julia = "1.10"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SpecialFunctions", "Random", "Test"]
